std = "lua51"
max_line_length = false

globals = {
    "CH",
    "ChamberlainDB",
    "SLASH_CH1",
    "SLASH_CH2",
    "SlashCmdList",
}

read_globals = {
    "C_Timer",
    "C_Housing",
    "C_ChatInfo",
    "CreateFrame",
    "UIParent",
    "UIFrameFadeIn",
    "UIFrameFadeOut",
    "UISpecialFrames",
    "UnitPosition",
    "UnitName",
    "UnitGUID",
    "IsInGroup",
    "IsInRaid",
    "GetNumGroupMembers",
    "UnitIsUnit",
    "LE_PARTY_CATEGORY_HOME",
    "LE_PARTY_CATEGORY_INSTANCE",
    "GetRealmName",
    "GetServerTime",
    "GetLocale",
    "CopyTable",
    "CreateColor",
    "GameTooltip",
    "GameFontNormal",
    "GameFontNormalSmall",
    "GameFontNormalLarge",
    "GameFontHighlightSmall",
    "GameFontDisableSmall",
    "_G",
    "PlaySound",
    "SOUNDKIT",
    "Minimap",
    "UnitClass",
    "RAID_CLASS_COLORS",
    "ColorPickerFrame",
    "GetCursorPosition",
    "IsMouseButtonDown",
    "C_Item",
    "C_Texture",
    "UnitIsVisible",
    "GetTime",
    "C_EncodingUtil",
    "wipe",
    "print",
    "math",
    "string",
    "table",
    "ipairs",
    "MenuUtil",
    "C_VoiceChat",
    "GetBuildInfo",
    "Enum",
    "UnitSex",
}
